openapi: 3.0.0
info:
  title: Restaurant POS API
  version: 1.0.0
  description: API for menu, users, and orders in MPEPOS Kitchen

servers:
  -url: https//api.mpepos.com

paths:
/auth/register:
  post:
    summary: Register a new user
    requestBody:
     required: true
     content: 
      application/json:
       schema:
         type: object
         properties:
           firstName: {type: string}
           lastName: {type: string}
           email: {type: string}
           username: { type: string}
           password: {type: string}

responses:
  '201;
    description: User registered

/auth/login:
post:
  summary: Login and get a token
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            username: {type: string}
            password: {type: string}
responses:
  '200'
   description: Successful login

/products;
get: 
  summary: Get all products
  responses:
   '200':
      description: List of products
      content:
        application/json:
         schema:
          type: array
          items:
            type: object
            properties:
             id: { type: string }
             name: { type: string}
             description: {type: string}
             prices:
               type: object
               properties:
                 Small: { type: number}
                 Medium: {type: number }
                 Large: { type: number }

/orders:
post:
  summary: Create a new order
  requestBody:
   required: true
   content:
     application/json:
     schema:
      type: object
      properties:
        products:
         type: array
         items:
           type: object
           properties:
             productId: { type: string}
             quantity: { type: string}
     size: {type: string}
    milk: { type; string}
responses:
'201':
description: Order created
